use_frameworks!

platform :ios, '8.0'

target 'LQNetWorkingModule_Example' do
  pod 'LQNetWorkingModule', :path => '../'

  target 'LQNetWorkingModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
